name: flood
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - cdsapi
  - geopandas
  - pyogrio
  - rasterio
  - earthengine-api
  - pytorch
  - pytorch-cuda 11.8
  - torchvision
  - einops
  - xarray
  - rioxarray
  - dask
  - netcdf4
  - richdem
  - asf_search
  - skimage
