name: flood
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - cdsapi
  - geopandas
  - pyogrio
  - rasterio
  - earthengine-api
  - pytorch
  - pytorch-cuda 11.8
  - torchvision
  - einops # for kurosiwo
  - vit-pytorch
  - xarray
  - rioxarray
